//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

using NMF.Collections.Generic;
using NMF.Collections.ObjectModel;
using NMF.Expressions;
using NMF.Expressions.Linq;
using NMF.Models;
using NMF.Models.Collections;
using NMF.Serialization;
using NMF.Utilities;
using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel;
using System.Diagnostics;
using System.Linq;

namespace NMFDemo.Metamodels.PN
{
    
    
    /// <summary>
    /// The public interface for Transition
    /// </summary>
    [DefaultImplementationTypeAttribute(typeof(Transition))]
    [XmlDefaultImplementationTypeAttribute(typeof(Transition))]
    public interface ITransition : IModelElement
    {
        
        /// <summary>
        /// The input property
        /// </summary>
        string Input
        {
            get;
            set;
        }
        
        /// <summary>
        /// The from property
        /// </summary>
        IListExpression<IPlace> From
        {
            get;
        }
        
        /// <summary>
        /// The to property
        /// </summary>
        IListExpression<IPlace> To
        {
            get;
        }
        
        /// <summary>
        /// Gets fired when the Input property changed its value
        /// </summary>
        event EventHandler InputChanged;
    }
}

