//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

using NMF.Collections.Generic;
using NMF.Collections.ObjectModel;
using NMF.Expressions;
using NMF.Expressions.Linq;
using NMF.Models;
using NMF.Models.Collections;
using NMF.Serialization;
using NMF.Utilities;
using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel;
using System.Diagnostics;
using System.Linq;

namespace NMFDemo.Metamodels.PN
{
    
    
    public class PlaceIncomingCollection : ObservableOppositeList<IPlace, ITransition>
    {
        
        public PlaceIncomingCollection(IPlace parent) : 
                base(parent)
        {
        }
        
        private void OnItemDeleted(object sender, EventArgs e)
        {
            this.Remove(((ITransition)(sender)));
        }
        
        protected override void SetOpposite(ITransition item, IPlace parent)
        {
            if ((parent == null))
            {
                item.Deleted += this.OnItemDeleted;
                item.To.Remove(this.Parent);
            }
            else
            {
                item.Deleted -= this.OnItemDeleted;
                item.To.Add(parent);
            }
        }
    }
}

