//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

using NMF.Collections.Generic;
using NMF.Collections.ObjectModel;
using NMF.Expressions;
using NMF.Expressions.Linq;
using NMF.Models;
using NMF.Models.Collections;
using NMF.Serialization;
using NMF.Utilities;
using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel;
using System.Diagnostics;
using System.Linq;

namespace NMFDemo.Metamodels.PN
{
    
    
    /// <summary>
    /// The representation of the Place class
    /// </summary>
    [XmlIdentifierAttribute("name")]
    [XmlNamespaceAttribute("http://github.com/NMFCode/Examples/PetriNet")]
    [XmlNamespacePrefixAttribute("pn")]
    [ModelRepresentationClassAttribute("http://github.com/NMFCode/Examples/PetriNet#//Place/")]
    [DebuggerDisplayAttribute("Place {Name}")]
    public class Place : ModelElement, IPlace, IModelElement
    {
        
        /// <summary>
        /// The backing field for the Name property
        /// </summary>
        private string _name;
        
        /// <summary>
        /// The backing field for the Incoming property
        /// </summary>
        private PlaceIncomingCollection _incoming;
        
        /// <summary>
        /// The backing field for the Outgoing property
        /// </summary>
        private PlaceOutgoingCollection _outgoing;
        
        public Place()
        {
            this._incoming = new PlaceIncomingCollection(this);
            this._incoming.CollectionChanged += this.IncomingCollectionChanged;
            this._outgoing = new PlaceOutgoingCollection(this);
            this._outgoing.CollectionChanged += this.OutgoingCollectionChanged;
        }
        
        /// <summary>
        /// The name property
        /// </summary>
        [XmlElementNameAttribute("name")]
        [IdAttribute()]
        [XmlAttributeAttribute(true)]
        public virtual string Name
        {
            get
            {
                return this._name;
            }
            set
            {
                if ((value != this._name))
                {
                    this._name = value;
                    this.OnNameChanged(EventArgs.Empty);
                    this.OnPropertyChanged("Name");
                }
            }
        }
        
        /// <summary>
        /// The incoming property
        /// </summary>
        [DesignerSerializationVisibilityAttribute(DesignerSerializationVisibility.Content)]
        [XmlElementNameAttribute("incoming")]
        [XmlAttributeAttribute(true)]
        [XmlOppositeAttribute(typeof(ITransition), "to")]
        public virtual IListExpression<ITransition> Incoming
        {
            get
            {
                return this._incoming;
            }
        }
        
        /// <summary>
        /// The outgoing property
        /// </summary>
        [DesignerSerializationVisibilityAttribute(DesignerSerializationVisibility.Content)]
        [XmlElementNameAttribute("outgoing")]
        [XmlAttributeAttribute(true)]
        [XmlOppositeAttribute(typeof(ITransition), "from")]
        public virtual IListExpression<ITransition> Outgoing
        {
            get
            {
                return this._outgoing;
            }
        }
        
        /// <summary>
        /// Gets the referenced model elements of this model element
        /// </summary>
        public override IEnumerableExpression<IModelElement> ReferencedElements
        {
            get
            {
                return base.ReferencedElements.Concat(new PlaceReferencedElementsCollection(this));
            }
        }
        
        /// <summary>
        /// Gets a value indicating whether the current model element can be identified by an attribute value
        /// </summary>
        public override bool IsIdentified
        {
            get
            {
                return true;
            }
        }
        
        /// <summary>
        /// Gets fired when the Name property changed its value
        /// </summary>
        public event EventHandler NameChanged;
        
        /// <summary>
        /// Raises the NameChanged event
        /// </summary>
        /// <param name="eventArgs">The event data</param>
        protected virtual void OnNameChanged(EventArgs eventArgs)
        {
            EventHandler handler = this.NameChanged;
            if ((handler != null))
            {
                handler.Invoke(this, eventArgs);
            }
        }
        
        /// <summary>
        /// Forwards change notifications for the Incoming property to the parent model element
        /// </summary>
        /// <param name="sender">The collection that raised the change</param>
        /// <param name="e">The original event data</param>
        private void IncomingCollectionChanged(object sender, System.Collections.Specialized.NotifyCollectionChangedEventArgs e)
        {
            this.OnCollectionChanged("Incoming", e);
        }
        
        /// <summary>
        /// Forwards change notifications for the Outgoing property to the parent model element
        /// </summary>
        /// <param name="sender">The collection that raised the change</param>
        /// <param name="e">The original event data</param>
        private void OutgoingCollectionChanged(object sender, System.Collections.Specialized.NotifyCollectionChangedEventArgs e)
        {
            this.OnCollectionChanged("Outgoing", e);
        }
        
        /// <summary>
        /// Gets the Class element that describes the structure of the current model element
        /// </summary>
        public override NMF.Models.Meta.IClass GetClass()
        {
            return NMF.Models.Repository.MetaRepository.Instance.ResolveClass("http://github.com/NMFCode/Examples/PetriNet#//Place/");
        }
        
        /// <summary>
        /// Gets the identifier string for this model element
        /// </summary>
        /// <returns>The identifier string</returns>
        public override string ToIdentifierString()
        {
            return this.Name.ToString();
        }
        
        /// <summary>
        /// The collection class to to represent the children of the Place class
        /// </summary>
        public class PlaceReferencedElementsCollection : ReferenceCollection, ICollectionExpression<IModelElement>, ICollection<IModelElement>
        {
            
            private Place _parent;
            
            /// <summary>
            /// Creates a new instance
            /// </summary>
            public PlaceReferencedElementsCollection(Place parent)
            {
                this._parent = parent;
            }
            
            /// <summary>
            /// Gets the amount of elements contained in this collection
            /// </summary>
            public override int Count
            {
                get
                {
                    int count = 0;
                    count = (count + this._parent.Incoming.Count);
                    count = (count + this._parent.Outgoing.Count);
                    return count;
                }
            }
            
            protected override void AttachCore()
            {
                this._parent.Incoming.AsNotifiable().CollectionChanged += this.PropagateCollectionChanges;
                this._parent.Outgoing.AsNotifiable().CollectionChanged += this.PropagateCollectionChanges;
            }
            
            protected override void DetachCore()
            {
                this._parent.Incoming.AsNotifiable().CollectionChanged -= this.PropagateCollectionChanges;
                this._parent.Outgoing.AsNotifiable().CollectionChanged -= this.PropagateCollectionChanges;
            }
            
            /// <summary>
            /// Adds the given element to the collection
            /// </summary>
            /// <param name="item">The item to add</param>
            public override void Add(IModelElement item)
            {
                ITransition incomingCasted = item.As<ITransition>();
                if ((incomingCasted != null))
                {
                    this._parent.Incoming.Add(incomingCasted);
                }
                ITransition outgoingCasted = item.As<ITransition>();
                if ((outgoingCasted != null))
                {
                    this._parent.Outgoing.Add(outgoingCasted);
                }
            }
            
            /// <summary>
            /// Clears the collection and resets all references that implement it.
            /// </summary>
            public override void Clear()
            {
                this._parent.Incoming.Clear();
                this._parent.Outgoing.Clear();
            }
            
            /// <summary>
            /// Gets a value indicating whether the given element is contained in the collection
            /// </summary>
            /// <returns>True, if it is contained, otherwise False</returns>
            /// <param name="item">The item that should be looked out for</param>
            public override bool Contains(IModelElement item)
            {
                if (this._parent.Incoming.Contains(item))
                {
                    return true;
                }
                if (this._parent.Outgoing.Contains(item))
                {
                    return true;
                }
                return false;
            }
            
            /// <summary>
            /// Copies the contents of the collection to the given array starting from the given array index
            /// </summary>
            /// <param name="array">The array in which the elements should be copied</param>
            /// <param name="arrayIndex">The starting index</param>
            public override void CopyTo(IModelElement[] array, int arrayIndex)
            {
                IEnumerator<IModelElement> incomingEnumerator = this._parent.Incoming.GetEnumerator();
                try
                {
                    for (
                    ; incomingEnumerator.MoveNext(); 
                    )
                    {
                        array[arrayIndex] = incomingEnumerator.Current;
                        arrayIndex = (arrayIndex + 1);
                    }
                }
                finally
                {
                    incomingEnumerator.Dispose();
                }
                IEnumerator<IModelElement> outgoingEnumerator = this._parent.Outgoing.GetEnumerator();
                try
                {
                    for (
                    ; outgoingEnumerator.MoveNext(); 
                    )
                    {
                        array[arrayIndex] = outgoingEnumerator.Current;
                        arrayIndex = (arrayIndex + 1);
                    }
                }
                finally
                {
                    outgoingEnumerator.Dispose();
                }
            }
            
            /// <summary>
            /// Removes the given item from the collection
            /// </summary>
            /// <returns>True, if the item was removed, otherwise False</returns>
            /// <param name="item">The item that should be removed</param>
            public override bool Remove(IModelElement item)
            {
                ITransition transitionItem = item.As<ITransition>();
                if (((transitionItem != null) 
                            && this._parent.Incoming.Remove(transitionItem)))
                {
                    return true;
                }
                if (((transitionItem != null) 
                            && this._parent.Outgoing.Remove(transitionItem)))
                {
                    return true;
                }
                return false;
            }
            
            /// <summary>
            /// Gets an enumerator that enumerates the collection
            /// </summary>
            /// <returns>A generic enumerator</returns>
            public override IEnumerator<IModelElement> GetEnumerator()
            {
                return Enumerable.Empty<IModelElement>().Concat(this._parent.Incoming).Concat(this._parent.Outgoing).GetEnumerator();
            }
        }
    }
}

