//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

using NMF.Collections.Generic;
using NMF.Collections.ObjectModel;
using NMF.Expressions;
using NMF.Expressions.Linq;
using NMF.Models;
using NMF.Models.Collections;
using NMF.Serialization;
using NMF.Utilities;
using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel;
using System.Diagnostics;
using System.Linq;

namespace NMFDemo.Metamodels.FSM
{
    
    
    /// <summary>
    /// The public interface for State
    /// </summary>
    [DefaultImplementationTypeAttribute(typeof(State))]
    [XmlDefaultImplementationTypeAttribute(typeof(State))]
    public interface IState : IModelElement
    {
        
        /// <summary>
        /// The name property
        /// </summary>
        string Name
        {
            get;
            set;
        }
        
        /// <summary>
        /// The isAccepting property
        /// </summary>
        bool IsAccepting
        {
            get;
            set;
        }
        
        /// <summary>
        /// The outgoing property
        /// </summary>
        IListExpression<ITransition> Outgoing
        {
            get;
        }
        
        /// <summary>
        /// The incoming property
        /// </summary>
        IListExpression<ITransition> Incoming
        {
            get;
        }
        
        /// <summary>
        /// Gets fired when the Name property changed its value
        /// </summary>
        event EventHandler NameChanged;
        
        /// <summary>
        /// Gets fired when the IsAccepting property changed its value
        /// </summary>
        event EventHandler IsAcceptingChanged;
    }
}

