//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:6.0.13
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using NMF.Collections.Generic;
using NMF.Collections.ObjectModel;
using NMF.Expressions;
using NMF.Expressions.Linq;
using NMF.Models;
using NMF.Models.Collections;
using NMF.Models.Expressions;
using NMF.Models.Meta;
using NMF.Models.Repository;
using NMF.Serialization;
using NMF.Utilities;
using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel;
using System.Diagnostics;
using System.Linq;

namespace NMFDemo.Metamodels.FSM
{
    
    
    /// <summary>
    /// The public interface for Transition
    /// </summary>
    [DefaultImplementationTypeAttribute(typeof(Transition))]
    [XmlDefaultImplementationTypeAttribute(typeof(Transition))]
    [ModelRepresentationClassAttribute("http://github.com/NMFCode/Examples/FiniteStateMachines#//Transition")]
    public interface ITransition : IModelElement
    {
        
        /// <summary>
        /// The input property
        /// </summary>
        [DisplayNameAttribute("input")]
        [CategoryAttribute("Transition")]
        [XmlElementNameAttribute("input")]
        [XmlAttributeAttribute(true)]
        string Input
        {
            get;
            set;
        }
        
        /// <summary>
        /// The source property
        /// </summary>
        [BrowsableAttribute(false)]
        [XmlElementNameAttribute("source")]
        [DesignerSerializationVisibilityAttribute(DesignerSerializationVisibility.Hidden)]
        [XmlAttributeAttribute(true)]
        [XmlOppositeAttribute("outgoing")]
        IState Source
        {
            get;
            set;
        }
        
        /// <summary>
        /// The target property
        /// </summary>
        [DisplayNameAttribute("target")]
        [CategoryAttribute("Transition")]
        [XmlElementNameAttribute("target")]
        [XmlAttributeAttribute(true)]
        [XmlOppositeAttribute("incoming")]
        IState Target
        {
            get;
            set;
        }
        
        /// <summary>
        /// Gets fired before the Input property changes its value
        /// </summary>
        event System.EventHandler<ValueChangedEventArgs> InputChanging;
        
        /// <summary>
        /// Gets fired when the Input property changed its value
        /// </summary>
        event System.EventHandler<ValueChangedEventArgs> InputChanged;
        
        /// <summary>
        /// Gets fired before the Source property changes its value
        /// </summary>
        event System.EventHandler<ValueChangedEventArgs> SourceChanging;
        
        /// <summary>
        /// Gets fired when the Source property changed its value
        /// </summary>
        event System.EventHandler<ValueChangedEventArgs> SourceChanged;
        
        /// <summary>
        /// Gets fired before the Target property changes its value
        /// </summary>
        event System.EventHandler<ValueChangedEventArgs> TargetChanging;
        
        /// <summary>
        /// Gets fired when the Target property changed its value
        /// </summary>
        event System.EventHandler<ValueChangedEventArgs> TargetChanged;
    }
}

